spring:
  data:
    mongodb:
      auto-index-creation: true
      database: MoviesDB
      uri: mongodb+srv://${username}:${password}@mongodb.ldc9z5l.mongodb.net/?retryWrites=true&w=majority
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAILPASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write-timeout: 10000
          connection-timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080
      
security:
  jwt:
    secret-key: verysecretkeydonttellanybody
